services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # depends_on:
    #   - backend
    #   - mongodb
    #   - mysql
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes: 
      - ./backend:/app 

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: my_db
    volumes:
      - mysql_data:/var/lib/mysql

  ollama:
    image: ollama/ollama
    container_name: ollama_ai
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama

volumes:
  mongo_data:
  mysql_data: